// Code generated by entc, DO NOT EDIT.

package person

const (
	// Label holds the string label denoting the person type in the database.
	Label = "person"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIsGiantSwarmEmployee holds the string denoting the isgiantswarmemployee field in the database.
	FieldIsGiantSwarmEmployee = "is_giant_swarm_employee"
	// EdgeGithubAccount holds the string denoting the github_account edge name in mutations.
	EdgeGithubAccount = "github_account"
	// GithubAccountLabel holds the string label denoting the github_account edge type in the database.
	GithubAccountLabel = "person_github_account"
)
