// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/__"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"github.com/giantswarm/graph/ent/githubuser"
	"github.com/giantswarm/graph/ent/predicate"
)

// GitHubUserDelete is the builder for deleting a GitHubUser entity.
type GitHubUserDelete struct {
	config
	hooks    []Hook
	mutation *GitHubUserMutation
}

// Where appends a list predicates to the GitHubUserDelete builder.
func (ghud *GitHubUserDelete) Where(ps ...predicate.GitHubUser) *GitHubUserDelete {
	ghud.mutation.Where(ps...)
	return ghud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ghud *GitHubUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ghud.hooks) == 0 {
		affected, err = ghud.gremlinExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GitHubUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ghud.mutation = mutation
			affected, err = ghud.gremlinExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ghud.hooks) - 1; i >= 0; i-- {
			if ghud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ghud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ghud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ghud *GitHubUserDelete) ExecX(ctx context.Context) int {
	n, err := ghud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ghud *GitHubUserDelete) gremlinExec(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := ghud.gremlin().Query()
	if err := ghud.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	return res.ReadInt()
}

func (ghud *GitHubUserDelete) gremlin() *dsl.Traversal {
	t := g.V().HasLabel(githubuser.Label)
	for _, p := range ghud.mutation.predicates {
		p(t)
	}
	return t.SideEffect(__.Drop()).Count()
}

// GitHubUserDeleteOne is the builder for deleting a single GitHubUser entity.
type GitHubUserDeleteOne struct {
	ghud *GitHubUserDelete
}

// Exec executes the deletion query.
func (ghudo *GitHubUserDeleteOne) Exec(ctx context.Context) error {
	n, err := ghudo.ghud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{githubuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ghudo *GitHubUserDeleteOne) ExecX(ctx context.Context) {
	ghudo.ghud.ExecX(ctx)
}
