// Code generated by entc, DO NOT EDIT.

package githubuser

const (
	// Label holds the string label denoting the githubuser type in the database.
	Label = "git_hub_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLogin holds the string denoting the login field in the database.
	FieldLogin = "login"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
)
