// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/gremlin/graph/dsl"
)

// Cluster is the predicate function for cluster builders.
type Cluster func(*dsl.Traversal)

// GitHubIssue is the predicate function for githubissue builders.
type GitHubIssue func(*dsl.Traversal)

// GitHubUser is the predicate function for githubuser builders.
type GitHubUser func(*dsl.Traversal)

// Person is the predicate function for person builders.
type Person func(*dsl.Traversal)
